;
CREATE EXTENSION IF NOT EXISTS btree_gist;
;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own profile"  ON profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users update own profile"  ON profiles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Landlord reads all profiles"  ON profiles FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord manages settings"  ON settings FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
INSERT INTO settings DEFAULT VALUES;
;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "properties_landlord_all" ON properties FOR ALL  USING (landlord_id = auth.uid());
CREATE POLICY "properties_staff_select" ON properties FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('landlord','caretaker')));
CREATE POLICY "properties_tenant_select" ON properties FOR SELECT  USING (EXISTS (    SELECT 1 FROM tenants t JOIN units u ON u.id = t.unit_id    WHERE t.user_id = auth.uid() AND u.property_id = properties.id  ));
;
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
CREATE POLICY "units_landlord_all" ON units FOR ALL  USING (property_id IN (SELECT id FROM properties WHERE landlord_id = auth.uid()));
CREATE POLICY "units_staff_select" ON units FOR SELECT  USING (property_id IN (SELECT id FROM properties));
CREATE POLICY "units_tenant_select" ON units FOR SELECT  USING (id IN (SELECT unit_id FROM tenants WHERE user_id = auth.uid()));
;
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant reads own record"  ON tenants FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Caretaker reads tenants"  ON tenants FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Landlord manages tenants"  ON tenants FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
;
CREATE SEQUENCE IF NOT EXISTS receipt_levy_seq START 1;
CREATE OR REPLACE FUNCTION generate_receipt_number(p_type text, p_year int)RETURNS text AS $$DECLARE  seq_val bigint;
  prefix  text;
BEGIN  IF p_type = 'rent' THEN    seq_val := nextval('receipt_rent_seq');
    prefix  := 'RENT';
  ELSE    seq_val := nextval('receipt_levy_seq');
    prefix  := 'LEVY';
  END IF;
  RETURN 'PSR-' || p_year::text || '-' || prefix || '-' || lpad(seq_val::text, 6, '0');
END;
$$ LANGUAGE plpgsql;
;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_receipt_number  BEFORE INSERT ON payments  FOR EACH ROW EXECUTE FUNCTION set_receipt_number();
;
;
;
ALTER TABLE applicants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord manages applicants"  ON applicants FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE POLICY "Public can submit application"  ON applicants FOR INSERT WITH CHECK (true);
;
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "files_landlord_all" ON files FOR ALL  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "files_tenant_select" ON files FOR SELECT  USING (tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid()));
CREATE POLICY "files_applicant_insert" ON files FOR INSERT  WITH CHECK (applicant_id IS NOT NULL);
;
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant manages own tickets"  ON tickets FOR SELECT USING (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Tenant inserts tickets"  ON tickets FOR INSERT WITH CHECK (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Caretaker reads all tickets"  ON tickets FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Caretaker updates tickets"  ON tickets FOR UPDATE USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Landlord manages tickets"  ON tickets FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE OR REPLACE FUNCTION update_ticket_timestamp()RETURNS TRIGGER AS $$BEGIN  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_ticket_updated  BEFORE UPDATE ON tickets  FOR EACH ROW EXECUTE FUNCTION update_ticket_timestamp();
;
ALTER TABLE inbox ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord reads inbox"  ON inbox FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE POLICY "Public can create inbox messages"  ON inbox FOR INSERT WITH CHECK (true);
;
ALTER TABLE activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff reads activity"  ON activity FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('landlord','caretaker'))  );
CREATE POLICY "Landlord manages activity"  ON activity FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
;
ALTER TABLE agreements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant reads own agreement"  ON agreements FOR SELECT USING (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Landlord manages agreements"  ON agreements FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notices_landlord_insert" ON notices FOR INSERT  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'landlord'));
CREATE POLICY "notices_auth_select" ON notices FOR SELECT  TO authenticated USING (true);
;
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "invitations_landlord_all" ON invitations FOR ALL  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "invitations_self_select" ON invitations FOR SELECT  USING (phone = (SELECT phone FROM profiles WHERE user_id = auth.uid()));
;
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "preferences_self_all" ON notification_preferences FOR ALL  USING (user_id = auth.uid());
CREATE POLICY "preferences_landlord_select" ON notification_preferences FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit_logs_landlord_select" ON audit_logs FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "audit_logs_system_insert" ON audit_logs FOR INSERT  WITH CHECK (true);
;
ALTER TABLE email_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "email_queue_service_insert" ON email_queue FOR INSERT WITH CHECK (true);
CREATE POLICY "email_queue_service_select" ON email_queue FOR SELECT USING (true);
CREATE POLICY "email_queue_service_update" ON email_queue FOR UPDATE USING (true);
;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER update_profiles_updated_at  BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_properties_updated_at  BEFORE UPDATE ON properties FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_units_updated_at  BEFORE UPDATE ON units FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_notification_prefs_updated_at  BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at();
;
;
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_properties_landlord ON properties(landlord_id);
CREATE INDEX IF NOT EXISTS idx_units_property ON units(property_id);
CREATE INDEX IF NOT EXISTS idx_units_status ON units(status);
CREATE INDEX IF NOT EXISTS idx_tenants_user_id ON tenants(user_id);
CREATE INDEX IF NOT EXISTS idx_tenants_property ON tenants(property_id);
CREATE INDEX IF NOT EXISTS idx_tenants_unit ON tenants(unit);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);
CREATE INDEX IF NOT EXISTS idx_payments_tenant_id ON payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_payments_property ON payments(property_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(date);
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments(paystack_ref);
CREATE INDEX IF NOT EXISTS idx_tickets_tenant_id ON tickets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tickets_property ON tickets(property_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_inbox_read ON inbox(read);
CREATE INDEX IF NOT EXISTS idx_activity_time ON activity(time DESC);
CREATE INDEX IF NOT EXISTS idx_files_tenant ON files(tenant_id);
CREATE INDEX IF NOT EXISTS idx_files_applicant ON files(applicant_id);
CREATE INDEX IF NOT EXISTS idx_notices_type ON notices(type);
CREATE INDEX IF NOT EXISTS idx_notices_sent ON notices(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_phone ON invitations(phone);
CREATE INDEX IF NOT EXISTS idx_agreements_tenant ON agreements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_agreements_status ON agreements(status);
CREATE INDEX IF NOT EXISTS idx_applicants_property ON applicants(property_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_queue_status ON email_queue(status);
;
