-- ================================================================-- PRINCESTEVE RESIDENCE — FULL PRODUCTION DATABASE SCHEMA-- Run this in your Supabase SQL editor for new deployments-- For existing deployments, run migrations in order:--   1. 20260704000001_multi_property.sql--   2. 20260704000002_file_storage.sql--   3. 20260704000003_enhanced_schema.sql--   4. 20260704000004_storage_rls.sql-- ================================================================-- Enable extensionsCREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS btree_gist;
-- ── PROFILES ─────────────────────────────────────────────────────CREATE TABLE profiles (  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),  user_id      uuid REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE NOT NULL,  role         text NOT NULL DEFAULT 'tenant'               CONSTRAINT check_role CHECK (role IN ('landlord','caretaker','tenant','applicant')),  full_name    text NOT NULL,  phone        text,  avatar_url   text,  email_verified boolean DEFAULT false,  last_login   timestamptz,  created_at   timestamptz NOT NULL DEFAULT now(),  updated_at   timestamptz NOT NULL DEFAULT now());
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own profile"  ON profiles FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users update own profile"  ON profiles FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Landlord reads all profiles"  ON profiles FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
-- ── SETTINGS ─────────────────────────────────────────────────────CREATE TABLE settings (  id               uuid PRIMARY KEY DEFAULT gen_random_uuid(),  property_name    text NOT NULL DEFAULT 'PrinceSteve Residence',  landlord_name    text NOT NULL DEFAULT 'Mrs. Ibadin R.E',  address          text NOT NULL DEFAULT '35 Godilove Street, Akowonjo Egbeda, Lagos',  emergency_phone  text DEFAULT '+2348054164910',  caretaker_name   text DEFAULT 'Steve',  caretaker_phone  text DEFAULT '+2348024427735',  bank_name        text DEFAULT 'First Bank Nigeria',  account_number   text DEFAULT '3012345678',  account_name     text DEFAULT 'Prince Steve Residence',  email            text DEFAULT 'beckydin63@gmail.com',  landlord_pin     text DEFAULT '1234',  caretaker_pin    text DEFAULT '5678',  tenant_pin       text DEFAULT '0000',  signature_url    text,  whatsapp_number  text,  updated_at       timestamptz NOT NULL DEFAULT now());
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord manages settings"  ON settings FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
INSERT INTO settings DEFAULT VALUES;
-- ── PROPERTIES (Multi-property support) ──────────────────────────CREATE TABLE properties (  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),  landlord_id  uuid REFERENCES profiles(user_id) NOT NULL,  name         text NOT NULL,  address      text NOT NULL,  description  text,  emergency_contact text,  caretaker_contact text,  bank_name    text DEFAULT 'First Bank Nigeria',  account_number text DEFAULT '3012345678',  account_name text DEFAULT 'Prince Steve Residence',  status       text NOT NULL DEFAULT 'active'                CONSTRAINT check_property_status CHECK (status IN ('active','inactive','maintenance')),  created_at   timestamptz NOT NULL DEFAULT now(),  updated_at   timestamptz NOT NULL DEFAULT now());
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
CREATE POLICY "properties_landlord_all" ON properties FOR ALL  USING (landlord_id = auth.uid());
CREATE POLICY "properties_staff_select" ON properties FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('landlord','caretaker')));
CREATE POLICY "properties_tenant_select" ON properties FOR SELECT  USING (EXISTS (    SELECT 1 FROM tenants t JOIN units u ON u.id = t.unit_id    WHERE t.user_id = auth.uid() AND u.property_id = properties.id  ));
-- ── UNITS ─────────────────────────────────────────────────────────CREATE TABLE units (  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),  property_id    uuid REFERENCES properties(id) NOT NULL,  name           text NOT NULL,  type           text NOT NULL CONSTRAINT check_unit_type CHECK (type IN ('apartment','shop','stall')),  occupied       boolean NOT NULL DEFAULT false,  status         text DEFAULT 'available'                  CONSTRAINT check_unit_status CHECK (status IN ('available','occupied','maintenance','unavailable')),  monthly_rent   numeric(12,2),  deposit_amount numeric(12,2),  description    text,  created_at     timestamptz NOT NULL DEFAULT now(),  updated_at     timestamptz NOT NULL DEFAULT now());
ALTER TABLE units ENABLE ROW LEVEL SECURITY;
CREATE POLICY "units_landlord_all" ON units FOR ALL  USING (property_id IN (SELECT id FROM properties WHERE landlord_id = auth.uid()));
CREATE POLICY "units_staff_select" ON units FOR SELECT  USING (property_id IN (SELECT id FROM properties));
CREATE POLICY "units_tenant_select" ON units FOR SELECT  USING (id IN (SELECT unit_id FROM tenants WHERE user_id = auth.uid()));
-- ── TENANTS ───────────────────────────────────────────────────────CREATE TABLE tenants (  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),  user_id             uuid REFERENCES auth.users(id) ON DELETE SET NULL,  property_id         uuid REFERENCES properties(id) NOT NULL,  name                text NOT NULL,  phone               text NOT NULL,  phone2              text,  email               text,  sex                 text,  state_of_origin     text,  tribe               text,  lga                 text,  home_address        text,  nationality         text DEFAULT 'Nigerian',  religion            text,  reason_moving       text,  occupation          text,  employer            text,  employer_address    text,  employer_duration   text,  job_title           text,  office_phone        text,  guarantor           text,  guarantor_address   text,  guarantor_phone     text,  guarantor_occupation text,  nin                 text,          -- Encrypted at rest, landlord-only  unit                text NOT NULL,  unit_id             uuid REFERENCES units(id),  type                text NOT NULL CONSTRAINT check_tenant_unit_type CHECK (type IN ('apartment','shop','stall')),  lease_start         date NOT NULL,  lease_end           date NOT NULL,  rent                numeric(15,2) NOT NULL,  security_deposit    numeric(15,2),  pay_freq            text NOT NULL DEFAULT 'annual'                       CONSTRAINT check_pay_freq CHECK (pay_freq IN ('annual','bi-annual','quarterly','monthly')),  status              text NOT NULL DEFAULT 'active'                       CONSTRAINT check_tenant_status CHECK (status IN ('active','vacated','pending')),  photo               text,          -- base64 or storage URL  notes               text,  approved_by         uuid REFERENCES profiles(user_id),  created_at          timestamptz NOT NULL DEFAULT now(),  updated_at          timestamptz NOT NULL DEFAULT now());
ALTER TABLE tenants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant reads own record"  ON tenants FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Caretaker reads tenants"  ON tenants FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Landlord manages tenants"  ON tenants FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
-- ── RECEIPTS SEQUENCE FUNCTION ────────────────────────────────────CREATE SEQUENCE IF NOT EXISTS receipt_rent_seq START 1;
CREATE SEQUENCE IF NOT EXISTS receipt_levy_seq START 1;
CREATE OR REPLACE FUNCTION generate_receipt_number(p_type text, p_year int)RETURNS text AS $$DECLARE  seq_val bigint;
  prefix  text;
BEGIN  IF p_type = 'rent' THEN    seq_val := nextval('receipt_rent_seq');
    prefix  := 'RENT';
  ELSE    seq_val := nextval('receipt_levy_seq');
    prefix  := 'LEVY';
  END IF;
  RETURN 'PSR-' || p_year::text || '-' || prefix || '-' || lpad(seq_val::text, 6, '0');
END;
$$ LANGUAGE plpgsql;
-- ── PAYMENTS ──────────────────────────────────────────────────────CREATE TABLE payments (  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),  tenant_id         uuid REFERENCES tenants(id) NOT NULL,  property_id       uuid REFERENCES properties(id),  tenant_name       text NOT NULL,  unit              text NOT NULL,  type              text NOT NULL CONSTRAINT check_pay_type CHECK (type IN ('rent','levy')),  amount            numeric(15,2) NOT NULL CHECK (amount > 0),  method            text NOT NULL CONSTRAINT check_method CHECK (method IN ('cash','bank transfer','paystack')),  date              date NOT NULL,  period            text,  receipt_no        text UNIQUE,     -- Set by trigger, not frontend  status            text NOT NULL DEFAULT 'pending'                     CONSTRAINT check_pay_status CHECK (status IN ('pending','approved','rejected')),  is_partial        boolean NOT NULL DEFAULT false,  partial_of        numeric(15,2),  levy_breakdown    jsonb,  paystack_ref      text,  approved_by       uuid REFERENCES profiles(user_id),  approved_at       timestamptz,  notes             text,  created_at        timestamptz NOT NULL DEFAULT now());
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
-- Trigger: auto-generate receipt number on insertCREATE OR REPLACE FUNCTION set_receipt_number()RETURNS TRIGGER AS $$BEGIN  IF NEW.receipt_no IS NULL THEN    NEW.receipt_no := generate_receipt_number(NEW.type, EXTRACT(YEAR FROM NEW.date)::int);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_receipt_number  BEFORE INSERT ON payments  FOR EACH ROW EXECUTE FUNCTION set_receipt_number();
-- RLS: Tenant reads own payments onlyCREATE POLICY "Tenant reads own payments"  ON payments FOR SELECT USING (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
-- RLS: Caretaker CANNOT read payments (financial lockout)-- RLS: Landlord full accessCREATE POLICY "Landlord manages payments"  ON payments FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
-- ── APPLICANTS ────────────────────────────────────────────────────CREATE TABLE applicants (  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),  property_id          uuid REFERENCES properties(id),  name                 text NOT NULL,  phone                text NOT NULL,  phone2               text,  email                text,  sex                  text,  state_of_origin      text,  tribe                text,  lga                  text,  home_address         text,  nationality          text DEFAULT 'Nigerian',  religion             text,  reason_moving        text,  occupation           text,  employer             text,  employer_address     text,  employer_duration    text,  job_title            text,  office_phone         text,  guarantor            text,  guarantor_address    text,  guarantor_phone      text,  guarantor_occupation text,  nin                  text,  photo                text,  unit_type            text NOT NULL DEFAULT 'apartment',  move_in              date,  payment_status       text NOT NULL DEFAULT 'unpaid'                        CONSTRAINT check_app_pay_status CHECK (payment_status IN ('unpaid','proof-submitted','paid')),  payment_amount       numeric(15,2),  payment_date         date,  payment_ref          text,  payment_method       text,  depositor_name       text,  proof_image          text,  signature_data       text,  signature_type       text,  agreed_on            date,  unit_assigned        text,  stage                text NOT NULL DEFAULT 'form-submitted',  reviewed_by          uuid REFERENCES profiles(user_id),  submitted_at         timestamptz NOT NULL DEFAULT now(),  reviewed_at          timestamptz,  rejection_reason     text,  updated_at           timestamptz DEFAULT now());
ALTER TABLE applicants ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord manages applicants"  ON applicants FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE POLICY "Public can submit application"  ON applicants FOR INSERT WITH CHECK (true);
-- ── FILES / DOCUMENTS ────────────────────────────────────────────CREATE TABLE files (  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),  file_name     text NOT NULL,  file_type     text NOT NULL,  file_size     bigint,  storage_path  text,  storage_bucket text DEFAULT 'documents',  is_base64     boolean NOT NULL DEFAULT false,  base64_data   text,  uploaded_by   uuid REFERENCES profiles(user_id),  tenant_id     uuid REFERENCES tenants(id) ON DELETE SET NULL,  applicant_id  uuid REFERENCES applicants(id) ON DELETE SET NULL,  status        text NOT NULL DEFAULT 'pending'                  CONSTRAINT check_file_status CHECK (status IN ('pending','approved','rejected')),  rejection_reason text,  created_at    timestamptz NOT NULL DEFAULT now());
ALTER TABLE files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "files_landlord_all" ON files FOR ALL  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "files_tenant_select" ON files FOR SELECT  USING (tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid()));
CREATE POLICY "files_applicant_insert" ON files FOR INSERT  WITH CHECK (applicant_id IS NOT NULL);
-- ── TICKETS ───────────────────────────────────────────────────────CREATE TABLE tickets (  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),  tenant_id    uuid REFERENCES tenants(id) NOT NULL,  property_id  uuid REFERENCES properties(id),  tenant_name  text NOT NULL,  unit         text NOT NULL,  title        text NOT NULL,  description  text,  category     text NOT NULL DEFAULT 'Other',  status       text NOT NULL DEFAULT 'pending'               CONSTRAINT check_ticket_status CHECK (status IN ('pending','in-progress','resolved')),  priority     text NOT NULL DEFAULT 'medium'               CONSTRAINT check_priority CHECK (priority IN ('low','medium','high')),  notes        text,  resolved_by  text,  assigned_to  uuid REFERENCES profiles(user_id),  resolved_at  timestamptz,  created_at   timestamptz NOT NULL DEFAULT now(),  updated_at   timestamptz NOT NULL DEFAULT now());
ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant manages own tickets"  ON tickets FOR SELECT USING (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Tenant inserts tickets"  ON tickets FOR INSERT WITH CHECK (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Caretaker reads all tickets"  ON tickets FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Caretaker updates tickets"  ON tickets FOR UPDATE USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('caretaker','landlord'))  );
CREATE POLICY "Landlord manages tickets"  ON tickets FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE OR REPLACE FUNCTION update_ticket_timestamp()RETURNS TRIGGER AS $$BEGIN  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER trg_ticket_updated  BEFORE UPDATE ON tickets  FOR EACH ROW EXECUTE FUNCTION update_ticket_timestamp();
-- ── INBOX ─────────────────────────────────────────────────────────CREATE TABLE inbox (  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),  type         text NOT NULL CONSTRAINT check_inbox_type CHECK (type IN ('application','message','proof','agreement')),  from_name    text NOT NULL,  subject      text NOT NULL,  preview      text,  read         boolean NOT NULL DEFAULT false,  applicant_id uuid REFERENCES applicants(id) ON DELETE CASCADE,  tenant_id    uuid REFERENCES tenants(id) ON DELETE CASCADE,  created_at   timestamptz NOT NULL DEFAULT now());
ALTER TABLE inbox ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Landlord reads inbox"  ON inbox FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
CREATE POLICY "Public can create inbox messages"  ON inbox FOR INSERT WITH CHECK (true);
-- ── ACTIVITY LOG ──────────────────────────────────────────────────CREATE TABLE activity (  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),  icon       text NOT NULL DEFAULT 'ti-bolt',  color      text NOT NULL DEFAULT '#DCFCE7',  icon_color text NOT NULL DEFAULT '#16A34A',  text       text NOT NULL,  time       timestamptz NOT NULL DEFAULT now());
ALTER TABLE activity ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff reads activity"  ON activity FOR SELECT USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role IN ('landlord','caretaker'))  );
CREATE POLICY "Landlord manages activity"  ON activity FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
-- ── TENANCY AGREEMENTS ────────────────────────────────────────────CREATE TABLE agreements (  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),  tenant_id         uuid REFERENCES tenants(id) NOT NULL,  applicant_id      uuid REFERENCES applicants(id),  property_id       uuid REFERENCES properties(id),  unsigned_url      text,  signed_url        text,  signature_data    text,  signature_type    text,  signed_at         timestamptz,  lease_start       date,  lease_end         date,  rent_amount       numeric(15,2),  security_deposit  numeric(15,2),  status            text DEFAULT 'pending_signature'                      CONSTRAINT check_agreement_status CHECK (status IN ('pending_signature','signed','active','expired')),  created_at        timestamptz NOT NULL DEFAULT now(),  updated_at        timestamptz DEFAULT now());
ALTER TABLE agreements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Tenant reads own agreement"  ON agreements FOR SELECT USING (    tenant_id IN (SELECT id FROM tenants WHERE user_id = auth.uid())  );
CREATE POLICY "Landlord manages agreements"  ON agreements FOR ALL USING (    EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord')  );
-- ── NOTICES ───────────────────────────────────────────────────────CREATE TABLE notices (  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),  title        text NOT NULL,  content      text NOT NULL,  sender_id    uuid REFERENCES profiles(user_id),  sender_name  text NOT NULL,  recipient_id text NOT NULL DEFAULT 'ALL',  type         text NOT NULL DEFAULT 'General'                CONSTRAINT check_notice_type CHECK (type IN ('General','Renewal','Default','Maintenance')),  read_by      uuid[] DEFAULT '{}',  sent_at      timestamptz NOT NULL DEFAULT now());
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notices_landlord_insert" ON notices FOR INSERT  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE user_id = auth.uid() AND role = 'landlord'));
CREATE POLICY "notices_auth_select" ON notices FOR SELECT  TO authenticated USING (true);
-- ── INVITATIONS ───────────────────────────────────────────────────CREATE TABLE invitations (  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),  phone         text NOT NULL,  email         text,  full_name     text,  role          text NOT NULL DEFAULT 'tenant',  property_id   uuid REFERENCES properties(id),  unit_id       uuid REFERENCES units(id),  token         text NOT NULL UNIQUE,  status        text NOT NULL DEFAULT 'pending',  payment_history jsonb DEFAULT '[]'::jsonb,  notes         text,  invited_by    uuid REFERENCES profiles(user_id),  expires_at    timestamptz NOT NULL,  verified_at   timestamptz,  accepted_at   timestamptz,  created_at    timestamptz NOT NULL DEFAULT now());
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "invitations_landlord_all" ON invitations FOR ALL  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "invitations_self_select" ON invitations FOR SELECT  USING (phone = (SELECT phone FROM profiles WHERE user_id = auth.uid()));
-- ── NOTIFICATION PREFERENCES ──────────────────────────────────────CREATE TABLE notification_preferences (  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),  user_id             uuid REFERENCES profiles(user_id) UNIQUE NOT NULL,  sms_enabled         boolean NOT NULL DEFAULT true,  email_enabled       boolean NOT NULL DEFAULT true,  in_app_enabled      boolean NOT NULL DEFAULT true,  rent_reminders      boolean NOT NULL DEFAULT true,  payment_alerts      boolean NOT NULL DEFAULT true,  ticket_updates      boolean NOT NULL DEFAULT true,  maintenance_alerts  boolean NOT NULL DEFAULT true,  broadcast_messages  boolean NOT NULL DEFAULT true,  created_at          timestamptz NOT NULL DEFAULT now(),  updated_at          timestamptz NOT NULL DEFAULT now());
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;
CREATE POLICY "preferences_self_all" ON notification_preferences FOR ALL  USING (user_id = auth.uid());
CREATE POLICY "preferences_landlord_select" ON notification_preferences FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
-- ── AUDIT LOGS ────────────────────────────────────────────────────CREATE TABLE audit_logs (  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),  user_id     uuid REFERENCES profiles(user_id),  property_id uuid REFERENCES properties(id),  action      text NOT NULL,  entity_type text NOT NULL,  entity_id   uuid,  old_values  jsonb,  new_values  jsonb,  ip_address  inet,  user_agent  text,  created_at  timestamptz NOT NULL DEFAULT now());
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit_logs_landlord_select" ON audit_logs FOR SELECT  USING (EXISTS (SELECT 1 FROM profiles p WHERE p.user_id = auth.uid() AND p.role = 'landlord'));
CREATE POLICY "audit_logs_system_insert" ON audit_logs FOR INSERT  WITH CHECK (true);
-- ── EMAIL QUEUE ───────────────────────────────────────────────────CREATE TABLE email_queue (  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),  to_address  text NOT NULL,  subject     text NOT NULL,  html_body   text,  text_body   text,  status      text NOT NULL DEFAULT 'pending',  retry_count integer NOT NULL DEFAULT 0,  error       text,  created_at  timestamptz NOT NULL DEFAULT now(),  sent_at     timestamptz);
ALTER TABLE email_queue ENABLE ROW LEVEL SECURITY;
CREATE POLICY "email_queue_service_insert" ON email_queue FOR INSERT WITH CHECK (true);
CREATE POLICY "email_queue_service_select" ON email_queue FOR SELECT USING (true);
CREATE POLICY "email_queue_service_update" ON email_queue FOR UPDATE USING (true);
-- ── UPDATED_AT TRIGGER ────────────────────────────────────────────CREATE OR REPLACE FUNCTION update_updated_at()RETURNS TRIGGER AS $$BEGIN  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER update_profiles_updated_at  BEFORE UPDATE ON profiles FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_properties_updated_at  BEFORE UPDATE ON properties FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_units_updated_at  BEFORE UPDATE ON units FOR EACH ROW EXECUTE FUNCTION update_updated_at();
CREATE TRIGGER update_notification_prefs_updated_at  BEFORE UPDATE ON notification_preferences FOR EACH ROW EXECUTE FUNCTION update_updated_at();
-- ── VIEW: Multi-property financial summary ────────────────────────CREATE OR REPLACE VIEW landlord_financial_summary ASSELECT  p.id AS property_id,  p.name AS property_name,  t.id AS tenant_id,  t.unit,  t.name AS tenant_name,  t.rent AS annual_rent,  t.pay_freq,  t.lease_end,  COALESCE(SUM(pay.amount) FILTER (WHERE pay.type='rent' AND pay.status='approved'), 0) AS rent_paid,  COALESCE(SUM(pay.amount) FILTER (WHERE pay.type='levy' AND pay.status='approved'), 0) AS levy_paid,  t.rent - COALESCE(SUM(pay.amount) FILTER (WHERE pay.type='rent' AND pay.status='approved'), 0) AS outstandingFROM tenants tJOIN properties p ON p.id = t.property_idLEFT JOIN payments pay ON pay.tenant_id = t.idWHERE t.status = 'active'GROUP BY p.id, p.name, t.id, t.unit, t.name, t.rent, t.pay_freq, t.lease_end;
-- ── INDEXES ───────────────────────────────────────────────────────CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles(user_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);
CREATE INDEX IF NOT EXISTS idx_properties_landlord ON properties(landlord_id);
CREATE INDEX IF NOT EXISTS idx_units_property ON units(property_id);
CREATE INDEX IF NOT EXISTS idx_units_status ON units(status);
CREATE INDEX IF NOT EXISTS idx_tenants_user_id ON tenants(user_id);
CREATE INDEX IF NOT EXISTS idx_tenants_property ON tenants(property_id);
CREATE INDEX IF NOT EXISTS idx_tenants_unit ON tenants(unit);
CREATE INDEX IF NOT EXISTS idx_tenants_status ON tenants(status);
CREATE INDEX IF NOT EXISTS idx_payments_tenant_id ON payments(tenant_id);
CREATE INDEX IF NOT EXISTS idx_payments_property ON payments(property_id);
CREATE INDEX IF NOT EXISTS idx_payments_status ON payments(status);
CREATE INDEX IF NOT EXISTS idx_payments_date ON payments(date);
CREATE INDEX IF NOT EXISTS idx_payments_reference ON payments(paystack_ref);
CREATE INDEX IF NOT EXISTS idx_tickets_tenant_id ON tickets(tenant_id);
CREATE INDEX IF NOT EXISTS idx_tickets_property ON tickets(property_id);
CREATE INDEX IF NOT EXISTS idx_tickets_status ON tickets(status);
CREATE INDEX IF NOT EXISTS idx_inbox_read ON inbox(read);
CREATE INDEX IF NOT EXISTS idx_activity_time ON activity(time DESC);
CREATE INDEX IF NOT EXISTS idx_files_tenant ON files(tenant_id);
CREATE INDEX IF NOT EXISTS idx_files_applicant ON files(applicant_id);
CREATE INDEX IF NOT EXISTS idx_notices_type ON notices(type);
CREATE INDEX IF NOT EXISTS idx_notices_sent ON notices(sent_at DESC);
CREATE INDEX IF NOT EXISTS idx_invitations_token ON invitations(token);
CREATE INDEX IF NOT EXISTS idx_invitations_phone ON invitations(phone);
CREATE INDEX IF NOT EXISTS idx_agreements_tenant ON agreements(tenant_id);
CREATE INDEX IF NOT EXISTS idx_agreements_status ON agreements(status);
CREATE INDEX IF NOT EXISTS idx_applicants_property ON applicants(property_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_created ON audit_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_email_queue_status ON email_queue(status);
-- ── SEED DATA ──────────────────────────────────────────────────────INSERT INTO units (property_id, name, type, occupied, status, monthly_rent, deposit_amount)SELECT (SELECT id FROM properties ORDER BY created_at ASC LIMIT 1), name, type, occupied,  CASE WHEN occupied THEN 'occupied' ELSE 'available' END,  CASE type    WHEN 'apartment' THEN 500000    WHEN 'shop' THEN 800000    WHEN 'stall' THEN 300000  END,  CASE type    WHEN 'apartment' THEN 50000    WHEN 'shop' THEN 80000    WHEN 'stall' THEN 30000  ENDFROM (  VALUES    ('Apt 1', 'apartment', true),    ('Apt 2', 'apartment', true),    ('Apt 3', 'apartment', true),    ('Apt 4', 'apartment', false),    ('Shop 1', 'shop', true),    ('Shop 2', 'shop', false),    ('Stall 1', 'stall', false),    ('Stall 2', 'stall', true)  ) AS seed(name, type, occupied)WHERE NOT EXISTS (SELECT 1 FROM units WHERE name = seed.name);
